- .gitignore
- package-lock.json
- package.json
- src/types/DistributeUnions.ts
- src/types/ExtractPreciseValue.ts
- src/types/InvertPattern.ts
- src/types/Pattern.ts
- src/types/helpers.ts
- tests/distribute-unions.test.ts
Some small typechecking perf improvements
- Only recurse on plain objects
- Stop recursion after 4 level of nesting in `DistributeUnions<a>` to avoid unnecessarily traversing huge data structures looking for union types
> Improve perfs

- package-lock.json
- package.json
- src/PatternType.ts
- src/index.ts
- src/types/DeepExclude.ts
- src/types/DistributeUnions.ts
- src/types/ExtractPreciseValue.ts
- src/types/FindSelected.ts
- src/types/InvertPattern.ts
- src/types/IsMatching.ts
- src/types/Match.ts
- src/types/Pattern.ts
- src/types/helpers.ts
- tests/deep-exclude.test.ts
- tests/distribute-unions.test.ts
- tests/exhaustive-match.test.ts
- tests/helpers.test.ts
- tests/is-matching.test.ts
- tests/utils.ts
- tests/when.test.ts
- tsconfig.json
This PR is an attempt to solve the performance issue with exhaustive pattern matching on data structures containing large union types stated in this issue https://github.com/gvergnaud/ts-pattern/issues/16
Instead of computing the union of all the possible data structures permitted by the input type upfront, this PR implements a `DeepExclude<A, B>`  type that only generate the smallest union possible based on the type of each pattern.
This strategy seems pretty promising, but I'll run some benchmarks before merging this PR.
> Gabriel.vergnaud/better exhaustive matching

- README.md
- ROADMAP.md
- package-lock.json
- package.json
- src/index.ts
- src/types/DeepExclude.ts
- src/types/Match.ts
- tests/deep-exclude.test.ts
- tests/exhaustive-match.test.ts
- tests/multiple-patterns.test.ts
This PR adds support for matching several pattern on a single `.with()` clause.
```ts
type Input = 1 | 2 | 3 | 4 | 5 | 6;
const output = match<Input>(1)
.with(1, 2, x => {...}) // x: 1 | 2
.with(3, x => {...}) // x: 3
.with(4, 5, 6, x => {...}) // x: 4 | 5 | 6
.run();
```
> Add support for multiple patterns

- package-lock.json
- package.json
- src/types/Match.ts
- src/types/helpers.ts
- tests/multiple-patterns.test.ts
- tests/output-type.test.ts
the output type of a match expressions will now be inferred as the Union of the return types of all branches:
```ts
const output = match(x as number)
.with(1, () => "string")
.with(2, () => 20) // this used to raise a compilation error, because we were expecting that all branches had the same type
.with(__, () => true)
.exhaustive();
type T = typeof output // string | number | boolean
```
> Gabriel.vergnaud/infer output as a union 2

- README.md
- src/index.ts
- src/types/Match.ts
- tests/otherwise.test.ts
Hi !
Wouldnt it be relevant to pass the matched value to the `.otherwise()` handler ?
before:
```typescript
const value = computeValue();
const result = match(value)
.when(a, d => d * 2)
.when(b, d => d / 2)
.otherwise(() => value + 2);
```
after:
```typescript
const result = match(computeValue())
.when(a, d => d * 2)
.when(b, d => d / 2)
.otherwise(d => d + 2);
```
> Pass matched value to otherwise

- src/wildcards.ts
- tests/numbers.test.ts
`__.number` doesn't match `NaN`, but sometimes you might need to. Because `NaN !== NaN`, this PR adds a matcher function for `NaN`: `__.NaN`.
> Provide a matcher wildcard for NaN

- src/types/FindSelected.ts
- tests/find-selected.test.ts
- tests/nesting.test.ts
- tests/not.test.ts
This fixes a bug reported in issue #43 where type inference breaks when matching on something of type `any`.
The tradeoff is that patterns with more than 7 levels of nesting will be considered too deep while it used to be 9. I think that's reasonable.
> Fix not on anys

- examples/tsconfig.json
Fixing an issue when running `tsc` inside the examples directory from a newly cloned repo, it errors out like below:
```
node_modules/ts-pattern/dist/types/BuildMany.d.ts:18:110 - error TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the 'lib' compiler option to 'es2015' or later.
18 ] : never : data extends readonly (infer a)[] ? Update<a, value, Cast<tail, PropertyKey[]>>[] : data extends Set<infer a> ? Set<Update<a, value, Cast<tail, PropertyKey[]>>> : data extends Map<infer k, infer v> ? Map<k, Update<v, value, Cast<tail, PropertyKey[]>>> : Compute<Omit<data, Cast<head, PropertyKey>> & {
~~~
node_modules/ts-pattern/dist/types/BuildMany.d.ts:18:125 - error TS2583: Cannot find name 'Set'. Do you need to change your target library? Try changing the …
```
> Add lib es2015 to tsconfig

- package-lock.json
- package.json
- src/types/InvertPattern.ts
- src/types/Match.ts
- src/types/helpers.ts
- tests/instance-of.test.ts
- tests/intersection-and-union.test.ts
- tests/multiple-patterns.test.ts
- tests/not.test.ts
- tests/optional.test.ts
- tests/real-world.test.ts
- tests/tuples.test.ts
- tests/type-error.test.ts
- tests/types.test.ts
- tests/unions.test.ts
With the current version of ts-pattern, nothing prevents you from writing `.with` clauses that will never match any input because the case has already been handled in a previous close:
```ts
type Plan = 'free' | 'pro' | 'premium';
const welcome = (plan: Plan) => 
match(plan)
.with('free', () => 'Hello free user!')
.with('pro', () => 'Hello pro user!')
.with('pro', () => 'Hello awesome user!')
//      👆 This will never match!
//         We should exclude "pro"
//         from the input type to 
//         reject duplicated with clauses. 
.with('premium', () => 'Hello premium user!')
.exhaustive()
```
Initially, I was reluctant to narrow the input type on every call of `.with` because of type checking performance. TS-Pattern's exhaustive checking is pretty expensive because it not only …
> [narrowing] Make subsequent .with clause inherit narrowing

- README.md
- package-lock.json
- package.json
- src/internals/symbols.ts
- src/patterns.ts
- src/types/Pattern.ts
- tests/narrow.test.ts
This PR fixes issue https://github.com/gvergnaud/ts-pattern/issues/174, reporting that It's currently impossible re-export a pattern from an ES module due to the following TS error:
```
The inferred type of this node exceeds the maximum length the compiler will serialize. An explicit type annotation is needed.(7056)
```
The compiler currently tries to inline pattern types when generating type definitions for a module exporting a TS-Pattern pattern, but since these types can get pretty large, it stops inlining them after a char count threshold has been crossed. Here is a [Playground](https://www.typescriptlang.org/play?ts=5.0.4#code/JYWwDg9gTgLgBAbziAhjAxgCwDRwApwC+cAZlBCHAOQwDOAtGGjAKZQB2VA3HAPS9wYATzAtaALjgA3AKwA6AAxyAjAChV6CO1rxgtAGIQIyuAF58cnVGDsA5nwGBQcnWbtu2gCEUUE+aQpJACIUQNwAI0k8Sxhr …
> 🐛 fix: Allow re-exporting patterns from ES Modules

- package-lock.json
- package.json
- src/is-matching.ts
- tests/is-matching.test.ts
- tests/tsconfig.json
- tsconfig.json
Currently, you need to use `as const` on your pattern to make sure that type narrowing works as you intend:
```ts
type Pizza = { type: 'pizza', topping: string };
type Sandwich = { type: 'sandwich', condiments: string[] }
type Food =  Pizza | Sandwich;
declare const x: Food
const isPizza = isMatching({ type: 'pizza' })
const isPizzaConst = isMatching({ type: 'pizza' } as const)
if (isPizza(x)) x  // x: Food
if (isPizzaConst(x)) x  // x: Pizza
```
This isn't intentional. Th 2-arguments overload of isMatching doesn't have this problem. 
This PR fixes that.
> fix: make isMatching(p) infer the pattern as a const type parameter

- src/patterns.ts
The CJS build of TS-Pattern generates es5 javascript code, and turns the generator syntax into `regeneratorRuntime` calls, a function that's part of Babel's standard library:
```ts
(((t = {})[Symbol.iterator] = function () {
/*#__PURE__*/ return regeneratorRuntime.mark(function t() {
var r;
return regeneratorRuntime.wrap(function (t) {
// ...
}, t);
})();
}),
```
The issue is that there is no guarantee that this function is in scope where TS-Pattern's CJS build is executed. This is a microbundle bug that has a closed issue here: https://github.com/developit/microbundle/issues/708 it's supposedly fixed, but I still see this behavior with the latest version of micro bundle, so this PR just turns the only generator of TS-Pattern into an iterator object.
> fix: Make sure regeneratorRuntime isn't included in the cjs build

- README.md
- docs/roadmap.md
- src/patterns.ts
- src/types/Pattern.ts
- tests/wildcards.test.ts
Add a new `P.nonNullable` pattern that will match any value except `null` or `undefined`.
```ts
import { match, P } from 'ts-pattern';
const input = null;
const output = match<number | null | undefined>(input)
.with(P.nonNullable, () => 'it is a number!')
.otherwise(() => 'it is either null or undefined!');
console.log(output);
// => 'it is either null or undefined!'
```
Closes #60 #154 #190 and will be a work-around for #143.
> feat: Add P.nonNullable patterns

- src/patterns.ts
Thanks for an awesome library 👍 
`P.map` jsdoc looks like it was copypasted from `P.set`.
- Updated  `P.map` jsdoc based on readme section on `P.map`
> chore: add P.map specific jsdoc for P.map

- package-lock.json
- package.json
- src/types/IsMatching.ts
- tests/type-is-matching.test.ts
- tests/wildcards.test.ts
Fixes issue https://github.com/gvergnaud/ts-pattern/issues/247
The when combining `P.nonNullable` and `P.nullish`, you should get an exhaustive pattern matching expression, but the following case was incorrectly considered non-exhaustive:
```ts 
declare const input: {
nested: string | number | null | undefined;
};
const res = match(input)
.with({ nested: P.nonNullable }, (x) => {/* ... */})
.with({ nested: P.nullish }, (x) => {/* ... */})
// should type-check
.exhaustive();
```
This is fixed now.
> fix: exhaustive checking with nested P.nonNullable patterns

- README.md
Hey, nice project! As I was reading the `README.md` file, I came across a typo in the code example for `P.when` patterns, which causes TypeScript issues. I would be happy to make any further adjustments as needed. Please feel free to close the PR if you think this change is unnecessary.
> docs: fix typo in `P.when` patterns code example

- src/errors.ts
- src/index.ts
- src/match.ts
- tests/exhaustive-match.test.ts
This adds/exports a custom `ExhaustiveError` which will be thrown at runtime when a `match` input doesn't match any pattern and `.exhaustive()` has been specified. This gives better error handling capabilities, for example when trying to distinguish between an unmatched pattern error and an error thrown within a matched pattern's callback.
Resolves #269
> feat: throw custom `ExhaustiveError` when no matched pattern

- src/types/BuildMany.ts
- src/types/DistributeUnions.ts
```
tsc --project tests/tsconfig.json --noEmit --extendedDiagnostics
```
| **Category** | **Before** | **After** | **Evolution (%)** |
| --- | --- | --- | --- |
| Files | 206 | 206 | 0% |
| Lines of Library | 40,612 | 40,612 | 0% |
| Lines of Definitions | 27,266 | 27,266 | 0% |
| Lines of TypeScript | 16,129 | 16,149 | 0.12% |
| Lines of JavaScript | 0 | 0 | - |
| Lines of JSON | 0 | 0 | - |
| Lines of Other | 0 | 0 | - |
| Identifiers | 121,119 | 121,150 | 0.03% |
| Symbols | 854,220 | 861,962 | 0.93% |
| Types | 435,316 | 432,599 | -0.65% |
| Instantiations | 6,735,991 | 4,562,378 | -32.33% |
| Memory used | 732,233K | 746,454K | 1.95% |
| Assignability cache size | 209,959 | 205,926 | -1.92% |
| Identity cache size | 28,093 | 28,250 | 0.56% |
| Subtype cache size | 2,944 | 2,944 | 0% …
> perf: improve type checking performance of BuildMany

- src/types/InvertPattern.ts
- tests/exhaustive-match.test.ts
- tests/lists.test.ts
This PR resolves the issue https://github.com/gvergnaud/ts-pattern/issues/271
Fixed the issue by modifying `InvertPatternForExcludeInternal` to consider `readonly` .
> Fixes type `InvertPatternForExcludeInternal` to work with readonly array

- package.json
- src/types/index.ts
Fix issue: https://github.com/gvergnaud/ts-pattern/issues/291
Export `Pattern.d.ts` in the package.json to solve the issue. They are now available at `ts-pattern/types`.
Doing the same changes from this PR in [this playground](https://codesandbox.io/p/devbox/r2jp93?file=%2Fmy-package%2Fexample.ts%3A9%2C21) fixes the TS error
> Export Pattern types in package.json

- package-lock.json
- package.json
- src/is-matching.ts
- src/patterns.ts
- src/types/FindSelected.ts
- src/types/Pattern.ts
- tests/infer.test.ts
- tests/is-matching.test.ts
- tests/matcher-protocol.test.ts
- tests/not.test.ts
This release contains two changes:
It used to be possible to pass a pattern than could never match to `isMatching`. The new version checks that the provide pattern does match the value in second parameter:
```ts
type Pizza = { type: 'pizza'; topping: string };
type Sandwich = { type: 'sandwich'; condiments: string[] };
type Food = Pizza | Sandwich;
const fn = (food: Pizza | Sandwich) => {
if (isMatching({ type: 'oops' }, food)) {
//                  👆 used to type-check, now doesn't!
}
}
```
When using `P.infer<Pattern>` to type a function argument, like in the following example: 
```ts
const getWithDefault = <T extends P.Pattern>(
input: unknown,
pattern: T,
defaultValue: P.infer<T> //  👈
): P.infer<T> =>
isMatching(pattern, input) ? input : defaultValue
```
TypeScript could get confused …
> Improvements to `P.infer` and `isMatching`

- package-lock.json
- package.json
- src/is-matching.ts
- src/types/Pattern.ts
- tests/is-matching.test.ts
The previous release introduced a bug with `isMatching` which made it unable to narrow union types properly, and would make it reject patterns containing extra unknown properties. This PR fixes this
```ts
type Pizza = { type: 'pizza'; topping: string };
type Sandwich = { type: 'sandwich'; condiments: string[] };
type Food = Pizza | Sandwich;
const food = { type: 'pizza', topping: 'cheese' } as Food;
// These patterns used to be reject, but now work:
if (isMatching({ topping: 'cheese' }, food)) {
// food: Food & { topping: 'cheese' }
}
if (isMatching({ unknownProp: P.instanceOf(Error) }, food)) {
// food: Food & { unknownProp: Error }
}
```
> fix(isMatching): Allow unknown properties in pattern

- src/is-matching.ts
- src/patterns.ts
- tests/is-matching.test.ts
- tests/objects.test.ts
`isMatching` didn't have full feature parity with `match` in terms of type narrowing. This PR bridges the gap.
> isMatching: improve narrowing

- README.md
- package-lock.json
- package.json
- src/match.ts
- src/types/Match.ts
- tests/exhaustive-fallback.test.ts
Solves #144 #218 and replaces #38  #219
By default, `.exhaustive()` will throw an error if the input value wasn't handled by any `.with(...)` clause. This should only happen if your types are incorrect.
It is possible to pass your own handler function as a parameter to decide what should happen if an unexpected value has been received. You can for example throw your own custom error:
```ts
match(...)
.with(...)
.exhaustive((unexpected: unknown) => {
throw MyCustomError(unexpected);
})
```
Or log an error and return a default value:
```ts
match<string, number>(...)
.with(P.string, (str) => str.length)
.exhaustive((notAString: unknown) => {
console.log(`received an unexpected value: ${notAString}`);
return 0;
})
```
> feat(exhaustive): Add support for passing a fallback function

- jsr.json
- package-lock.json
- package.json
- src/types/BuildMany.ts
- src/types/InvertPattern.ts
- src/types/helpers.ts
- tests/deep-exclude.test.ts
- tests/exhaustive-match.test.ts
- tests/optional-props.test.ts
- tests/types.test.ts
This PR fixes #278
This new release fixes the following bug in exhaustiveness checking when matching on optional properties:
```ts
type Input = { type?: 'one' } | { type: 'two' };
const f1 = (input: Input) =>
match(input)
.with({ type: 'one' }, () => {})
.with({ type: 'two' }, () => {})
.exhaustive(); // shouldn't type-check, but does 👎
const f2 = (input: Input) =>
match(input)
.with({ type: 'one' }, () => {})
.with({ type: 'two' }, () => {})
.with({ type: undefined }, () => {}) // <- the type key needs to be present.
.exhaustive();  // shouldn't type-check, but does 👎
```
These two cases don't type check anymore. They fail with a `NonExhaustiveError<{ type?: undefined; }>`. To fix it, you should do:
```ts
type Input = { type?: 'one' } | { type: 'two' };
const f = (input: Input) => …
```
> fix(.exhaustive): optional discriminant

- README.md
- jsr.json
- package-lock.json
- package.json
- src/match.ts
- src/types/Match.ts
- tests/narrow.test.ts
Add a .narrow() method to force a deep type narrowing after a `.with` clause. See https://x.com/GabrielVergnaud/status/1795208610965782626
Example:
```ts
const fn = (input: { prop?: string }) =>
match(input)
.with({ prop: P.nullish.optional() }, () => false)
.narrow()
.otherwise(({ prop }) => {
//          ^? string
return true;
});
> feat: .narrow() method & typechecking perf improvement
